# Alacritty Configuration

[window]
  dimensions = { columns = 120, lines = 30 }
  padding = { x = 10, y = 7 }
  decorations = "full"
  dynamic_title = true
  opacity = 0.8

[scrolling]
  history = 10000
  multiplier = 2

[font]
  normal = { family = "Fira Code", style = "Regular" }
  bold = { family = "Fira Code", style = "Bold" }
  italic = { family = "Fira Code", style = "Italic" }
  size = 12.0

[colors]
  [colors.primary]
    background = '0x0D0D0D'  # Cor de fundo bem escura
    foreground = '0xD4D4D4'  # Cor de texto padrão
  [colors.normal]
    black = '0x0D0D0D'
    red = '0xFF5555'
    green = '0x50FA7B'
    yellow = '0xF1FA8C'
    blue = '0xBD93F9'
    magenta = '0xFF79C6'
    cyan = '0x8BE9FD'
    white = '0xF8F8F2'
  [colors.bright]
    black = '0x555555'
    red = '0xFF6E6E'
    green = '0x69FF94'
    yellow = '0xFFFFA5'
    blue = '0xD6ACFF'
    magenta = '0xFF92DF'
    cyan = '0xA4FFFF'
    white = '0xFFFFFF'

[cursor]
  style = "Block"
  unfocused_hollow = true

[mouse]
  hide_when_typing = true

[shell]
  program = "/bin/zsh"
  args = ["--login"]

[keyboard]
  bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
    { key = "Q", mods = "Control|Shift", action = "Quit" },
    { key = "T", mods = "Control|Shift", action = "CreateNewTab" },
    { key = "Tab", mods = "Control", action = "SelectNextTab" },
    { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
  ]

